---
title: "Global Analysis"
author: "Edoardo Diana"
date: "2025-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Carchiamo qui dei pattern ricorrenti nelle strutture dele networks.

Essi hanno un effetto determinante su come il networked system lavora :

  - Connected components and Strongly Connected components 

  - Path lengths and the Small-world effect

  - Motifs

  - Assortative Mixing

## Connected Component

La componente connessa di un grafo non dirtto è il set massimo di nodi tale che ogni coppia di nodi è connessa da un path.

Il Giant Component riempie la maggior parte della rete.

## Strongly Connected Components

2 nodi sono nello stesso Strongly Connected Components se sono a vicendnda raggiungibili mediante un directed path.

Formano una partizione del set dei vertici e definiscono una relazione di equivalenza tra nodi.

### Conclusione

In questo caso stiamo lavorando con una citation network, la quale è una rete aciclica.

Le reti aciclinche non hanno strongly connected components di dimensione maggiore di 1.
